/* currently trying to connect to a service from uros client
- created custom srv Average4 with 4 int inputs and 1 float output (the average)
- wrote my own Average4Request and Average4Response structs based on the .hpp generated by ROSIDL for the srv
- in setup(), initialized a client for the "average4" service, using NULL for type support since I'm manually defining the request/response structs
*/

#include <Arduino.h>
#include <micro_ros_platformio.h>

#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>

// ROS define message types
#include <std_msgs/msg/int32.h>
#include <std_msgs/msg/string.h>
#include <string.h>

// define custom srv (compiled .hpp)
//#include "my_service/srv/average4.hpp"
#include "average4_request.hpp"

#if !defined(MICRO_ROS_TRANSPORT_ARDUINO_SERIAL)
#error This example is only avaliable for Arduino framework with serial transport.
#endif

#define LED_PIN 2

// === ROS SETUP ===
// handle communication with ROS network, apply to multiple topics
rclc_executor_t executor;   // invokes callbacks & receives incoming events
rclc_support_t support;     // type supprt system, message content handling
rcl_allocator_t allocator;  // memory mgmt
rcl_node_t node;            // node object itself
rcl_publisher_t esp32_pub;  // handles outgoing events/data

// === JOYSTICK PUBLISHER ===
#define VRX_PIN 32
#define VRY_PIN 33
std_msgs__msg__Int32 joystick_msg;
rcl_timer_t joystick_timer;
const unsigned int joystick_timer_timeout = 50;

// === GOOSE PUBLISHER ===
// sends humourous "honk" message at a set interval
rcl_publisher_t goose_publisher;
std_msgs__msg__String goose_msg;
rcl_timer_t goose_timer;
const unsigned int goose_timer_timeout = 400;

// === LED SUBSCRIBER ===
#define LED_SUB_Pin 18
rcl_subscription_t subscriber;
std_msgs__msg__String received_msg;

// === ADD TWO INTS CLIENT ===
rcl_client_t average4_client;

// === ERROR HANDLING ===
#define RCCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){error_loop();}}
#define RCSOFTCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){}}

// error handle loop
void error_loop() {
  while(1) {
    delay(100);
  }
}

// === JOYSTICK PUBLISHER CALLBACK ===
// called by executor every 50ms
// reads joystick x-axis and publishes it to ROS topic
void joystick_timer_callback(rcl_timer_t * joystick_timer, int64_t last_call_time) {
  RCLC_UNUSED(last_call_time);
  if (joystick_timer != NULL) {
    joystick_msg.data = analogRead(VRX_PIN) - 2096; // relative to center
    RCSOFTCHECK(rcl_publish(&esp32_pub, &joystick_msg, NULL));
  }
}

// === GOOSE PUBLISHER CALLBACK ===
// called by executor every 400ms
// publishes "HONK" to ROS topic
void goose_timer_callback(rcl_timer_t * timer, int64_t last_call_time) {
  RCLC_UNUSED(last_call_time);
  if (timer != NULL) {

    const char* goose_sound = "HONK";

    strcpy(goose_msg.data.data, goose_sound); 
    goose_msg.data.size = strlen(goose_msg.data.data);
    
    RCSOFTCHECK(rcl_publish(&goose_publisher, &goose_msg, NULL));
  }
}

// === LED SUBSCRIBER CALLBACK ===
// called by executor when new message arrives on "led_control" topic
// turns LED on/off based on message content ("ON" or "OFF")
void subscriber_callback(const void * msgin) {
  const std_msgs__msg__String * msg = (const std_msgs__msg__String *)msgin;
  if(strcmp(msg->data.data, "ON") == 0) {
    digitalWrite(LED_SUB_Pin, HIGH);
  } else if(strcmp(msg->data.data, "OFF") == 0) {
    digitalWrite(LED_SUB_Pin, LOW);
  }
}

void setup() {
  pinMode(LED_PIN, OUTPUT);
  // wait 4s bcz agent takes a minute to boot
  delay(1000);
  digitalWrite(LED_PIN, HIGH);
  delay(1000);
  digitalWrite(LED_PIN, LOW);
  delay(1000);
  digitalWrite(LED_PIN, HIGH);
  delay(1000);
  digitalWrite(LED_PIN, LOW);

  // configure serial transport
  Serial.begin(115200);
  set_microros_serial_transports(Serial);
  delay(2000);

  // create allocator
  allocator = rcl_get_default_allocator();

  // create init_options
  RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));

  // create this device's node & name
  RCCHECK(rclc_node_init_default(&node, "esp32_node", "", &support));

  // create publisher
  RCCHECK(rclc_publisher_init_default(
    &esp32_pub,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32),
    "joystick_x_pub"));

  // create goose_publisher for mating_calls topic
  RCCHECK(rclc_publisher_init_default(
    &goose_publisher,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String),
    "goose_calls"));

  // create timer for joystick
  RCCHECK(rclc_timer_init_default(
    &joystick_timer,
    &support,
    RCL_MS_TO_NS(joystick_timer_timeout),
    joystick_timer_callback)); // removed NULL 5th param

  // create goose_timer
  RCCHECK(rclc_timer_init_default(
    &goose_timer,
    &support,
    RCL_MS_TO_NS(goose_timer_timeout),
    goose_timer_callback)); // removed NULL 5th param

  // create subscriber
  RCCHECK(rclc_subscription_init_default(
    &subscriber,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String),
    "led_control"));

  // intialize client for add_two_ints
  RCCHECK(rcl_client_init(
  &average4_client, // client
  &node, // node name
  NULL, // type support (not needed bcz manual type struct)
  "average4", // service name
  NULL)); // options

  // allocate goose_msg
  goose_msg.data.capacity = 10; // enough for "HONK" and null terminator
  goose_msg.data.data = (char *)malloc(goose_msg.data.capacity * sizeof(char));
  goose_msg.data.size = 0;
  goose_msg.data.data[0] = '\0'; // initialize as empty string

  // allocate received_msg
  received_msg.data.capacity = 10; // enough for "ON", "OFF" and null terminator
  received_msg.data.data = (char *)malloc(received_msg.data.capacity * sizeof(char));
  received_msg.data.size = 0;
  received_msg.data.data[0] = '\0'; // initialize as empty string

  // initialize joystick_msg
  joystick_msg.data = 0;

  // create executor
  RCCHECK(rclc_executor_init(&executor, &support.context, 5, &allocator)); // Changed to 2 handles
  RCCHECK(rclc_executor_add_timer(&executor, &joystick_timer));
  RCCHECK(rclc_executor_add_timer(&executor, &goose_timer));
  RCCHECK(rclc_executor_add_subscription(
    &executor,
    &subscriber,
    &received_msg,
    &subscriber_callback,
    ON_NEW_DATA));

  // define joystick input
  pinMode(VRX_PIN, INPUT);
  pinMode(VRY_PIN, INPUT);
}

void loop() {
  delay(100);
  RCLC_UNUSED(rclc_executor_spin_some(&executor, RCL_MS_TO_NS(100)));

  // send average4 request every 5 tick
  // static int counter = 0;
  // if (counter++ >= 5) {
  //   for (int i = 0; i < 5; i++) {
  //     digitalWrite(LED_PIN, HIGH);
  //     delay(100);
  //     digitalWrite(LED_PIN, LOW);
  //     delay(100);
  //   }
  //   digitalWrite(LED_PIN, HIGH);
  //   counter = 0;
  //   Average4Request request;
  //   Average4Response response;
  //   request.input1 = 10;
  //   request.input2 = 20;
  //   request.input3 = 30;
  //   request.input4 = 40;
  //   int64_t sequence_id;
  //   RCSOFTCHECK(rcl_send_request(&average4_client, &request, &sequence_id));
    
  //   // Wait for response (blocking, simpler approach)
  //   // if (rcl_take_response(&average4_client, &sequence_id, &response) == RCL_RET_OK) {
  //   //   Serial.printf("Response: %f\n", response.output_value);
  //   // }

  //   // Block until response
  //   rmw_request_id_t request_id = {0};
  //   int sequence_number = 10; // Initialize sequence_id, picked a random number
  //   request_id.sequence_number = sequence_number;

  //   while (rcl_take_response(&average4_client, &request_id, &response) != RCL_RET_OK) {
  //       usleep(10000); // 10ms
  //       digitalWrite(LED_PIN, LOW);
  //       delay(50); // 100ms // flash while waiting for response
  //       digitalWrite(LED_PIN, HIGH);
  //   }
  //   digitalWrite(LED_PIN, LOW);
  // }
}
