; you gotta add board_microros_distro or else rmw build issue
[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_microros_distro = jazzy
board_microros_transport = serial
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/ros2/example_interfaces
board_microros_extra_packages = 
    example_interfaces
    my_service